1、重新抛出异常，如果使用方法e.fillInStackTrace() 将重新抛出异常的栈信息加入堆栈信息中
 之前的堆栈异常信息将丢失  某种程度上等同于抛出另一种异常

2、如果try：finally中try语句块抛出异常，若不处理，这里的异常就会丢失，
不管你这里的异常有没有处理都会执行fianlly方法 导致这里代码块的异常丢失

3、因为他的父类此方法并没有抛出异常所以在子类中抛出异常是不允许的
 但是如果抛出异常,则子类中的方法可以选择不抛出此类异常；也可以抛出这
 异常的子类或本身
 
 4、方法说明：方法名+形参。所以不能根据异常来判定是否重载了方法
    也不能只根据返回类型的不同来判定重载方法